### ISSUE TITLE
Propagate errors raised by low-level calls

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#96]
## 📚 Context

In order to allow DApp developers to perform any conceivable message call from the context of a DApp, we allow vouchers to execute a low-level message call. The return value of such a low-level call are a boolean flag (whether the call was successful or reverted) and some data (which can be either the return values of a function call or error data, depending on the value of the aforementioned success flag).

Currently, we are only checking whether the call was successful and ignoring the returned data altogether. This means that any error data which could be valuable for DApp developers to debug is suppressed and doesn't make it to the UI.

## ✔️ Solution

One solution is to propagate the error to the user. We could do this ourselves, but I've just recently found that OpenZeppelin implements this in their [`Address.sol`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol) library. The nice thing about this library is that it also implements this error handling for `DELEGATECALL`, which we hope to use with the [Output Unification](#42).

As a result, any call to `executeVoucher` with enough gas either returns `true` or propagates the error originally raised by the sub-call. Smart contracts can still do error handling by means of try-and-catch clauses.

**Comment by ZzzzHui** [comment]
In our implementation, return data from a low-level call is only propagated when the call reverted. However, should we worry about the case when the low-level call executes without reverting but returns false?
For example, let's say a voucher is an erc20 `transferFrom` call. When trying to execute the voucher, the `from` address doesn't have enough balance at that moment. Depending on the implementation, `transferFrom` could revert or return `false`. If the latter, then `success` is `true` (because it didn't revert) and `returndata` is `false`.
Should we propagate `returndata` even when `success` is `true`? Or we leave the issue to the dapp developers, for example, to call an intermediary contract that handles similar issues on a case-by-case basis.
@cartesi/rollups-unit

**Comment by guidanoli** [comment]
> However, should we worry about the case when the low-level call executes without reverting but returns false?

This is yet another use case for `DELEGATECALL` vouchers. Checking if the return value is `false` is only a specific case of a more general desire to process the return value of a function call. All of this will be possible with `DELEGATECALL`.

**Comment by guidanoli** [comment]
> Should we propagate returndata even when success is true?

That is a great question! We could make `executeVoucher` return this `returndata` if it is called by a smart contract, so that it can do whatever it wants with it. We can also emit this `returndata` in an event so it can be processed off-chain.

**Comment by ZzzzHui** [comment]
Yeah. In case of success, emitting the `returndata` in event like `VoucherExecuted` is the straightforward solution, although it cause more gas, especially if the called function returns more than just a boolean. Furthur optimizations would be possible with DELEGATECALL vouchers

**Comment by guidanoli** [comment]
> Further optimizations would be possible with DELEGATECALL vouchers.

Yes, I agree. Maybe we decide not to emit events by default and create a small smart contract that calls `executeVoucher` on any address that implements `ICartesiDApp` and emits the return data as an event so that the user has the option to waste more gas to debug things or not.

**Comment by ZzzzHui** [comment]
For the record, the discussion is also going on [here](https://discord.com/channels/600597137524391947/1161349703217188864) in Discord
